version: '3.7'

services:
  remnawave-bot:
    build: .
    container_name: promo-remna-bot
    restart: unless-stopped
    
    # Environment variables
    env_file:
      - .env
    
    # Volumes for persistent data
    volumes:
      - ./subscription_files:/app/subscription_files
      - ./logs:/app/logs
    
    # Network settings
    networks:
      - remnawave-network
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'
    
    # Health check
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('https://api.telegram.org', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  remnawave-network:
    driver: bridge